jobs:
  build:
    docker:
      - image: node:6-alpine
    steps:
      - run: apk add --update --no-cache git openssh-client
      - checkout
      - restore_cache:
          key: dependency-{{ .Environment.CACHE_KEY }}-{{ checksum "yarn.lock" }}
      - run: yarn global add ci-yarn-upgrade
      - run: yarn install
      - run: yarn lint
      - run: yarn compile
      - run: echo 'export PATH=$HOME/.yarn/bin:$PATH' >> $BASH_ENV
      - run: ci-yarn-upgrade --verbose
      - run: yarn test
      - save_cache:
          key: dependency-{{ .Environment.CACHE_KEY }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: upgrade and make PR
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" -a -n "${YARN_UPGRADE}" ]; then
              ci-yarn-upgrade --execute --verbose;
            fi
