jobs:
  build:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - restore_cache:
          key: dependency-{{ .Environment.CACHE_KEY }}-{{ checksum "yarn.lock" }}
      - run: yarn global add ci-yarn-upgrade
      - run: yarn install
      - run: yarn lint
      - run: yarn compile
      - run: ci-yarn-upgrade --verbose
      - run: yarn test
      - save_cache:
          key: dependency-{{ .Environment.CACHE_KEY }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: upgrade and make PR
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" -a -n "${YARN_UPGRADE}" ]; then
              ci-yarn-upgrade --execute --verbose;
            fi
